[project]
name = "chandan-aiops"
version = "1.4.0"
description = "Add your description here"
#chandan = "chandan_aiops.cli:main"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "build>=1.4.0",
    "setuptools>=80.10.2",
    "twine>=6.2.0",
    "wheel>=0.46.3",
]
